# Generated by Django 4.2.20 on 2025-05-11 03:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0002_location_game_winner_alter_team_name_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='team',
            name='name',
            field=models.CharField(blank=True, choices=[('Duke Blue Devils', 'Duke Blue Devils'), ('North Carolina Tar Heels', 'North Carolina Tar Heels'), ('Syracuse Orange', 'Syracuse Orange'), ('Florida State Seminoles', 'Florida State Seminoles'), ('Louisville Cardinals', 'Louisville Cardinals'), ('Virginia Cavaliers', 'Virginia Cavaliers'), ('Miami Hurricanes', 'Miami Hurricanes'), ('Clemson Tigers', 'Clemson Tigers'), ('Virginia Tech Hokies', 'Virginia Tech Hokies'), ('NC State Wolfpack', 'NC State Wolfpack'), ('Michigan Wolverines', 'Michigan Wolverines'), ('Indiana Hoosiers', 'Indiana Hoosiers'), ('Ohio State Buckeyes', 'Ohio State Buckeyes'), ('Wisconsin Badgers', 'Wisconsin Badgers'), ('Purdue Boilermakers', 'Purdue Boilermakers'), ('Michigan State Spartans', 'Michigan State Spartans'), ('Minnesota Golden Gophers', 'Minnesota Golden Gophers'), ('Maryland Terrapins', 'Maryland Terrapins'), ('Illinois Fighting Illini', 'Illinois Fighting Illini'), ('Iowa Hawkeyes', 'Iowa Hawkeyes'), ('Kansas Jayhawks', 'Kansas Jayhawks'), ('Baylor Bears', 'Baylor Bears'), ('Texas Longhorns', 'Texas Longhorns'), ('Oklahoma Sooners', 'Oklahoma Sooners'), ('Kansas State Wildcats', 'Kansas State Wildcats'), ('Texas Tech Red Raiders', 'Texas Tech Red Raiders'), ('West Virginia Mountaineers', 'West Virginia Mountaineers'), ('TCU Horned Frogs', 'TCU Horned Frogs'), ('Kentucky Wildcats', 'Kentucky Wildcats'), ('Florida Gators', 'Florida Gators'), ('Auburn Tigers', 'Auburn Tigers'), ('Alabama Crimson Tide', 'Alabama Crimson Tide'), ('Tennessee Volunteers', 'Tennessee Volunteers'), ('Arkansas Razorbacks', 'Arkansas Razorbacks'), ('Mississippi State Bulldogs', 'Mississippi State Bulldogs'), ('South Carolina Gamecocks', 'South Carolina Gamecocks'), ('Missouri Tigers', 'Missouri Tigers'), ('LSU Tigers', 'LSU Tigers')], help_text='Select if located in the United States.', max_length=100, null=True),
        ),
    ]
