# Generated by Django 4.2.20 on 2025-04-26 06:34

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0002_game_location'),
    ]

    operations = [
        migrations.CreateModel(
            name='Location',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('location', models.CharField(blank=True, max_length=200)),
            ],
        ),
        migrations.RemoveField(
            model_name='game',
            name='location',
        ),
    ]
