# Generated by Django 4.2.20 on 2025-04-26 06:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0003_location_remove_game_location'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='location',
            name='location',
        ),
        migrations.AddField(
            model_name='game',
            name='location',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='location', to='picks.location'),
        ),
        migrations.AddField(
            model_name='location',
            name='place',
            field=models.CharField(blank=True, max_length=200, null=True),
        ),
    ]
