# Generated by Django 4.2.20 on 2025-05-11 05:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('picks', '0003_alter_team_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='team',
            name='logo_url',
            field=models.URLField(blank=True, null=True),
        ),
    ]
